# Generated by Django 3.0.5 on 2023-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_selected_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regions',
            field=models.CharField(blank=True, choices=[('region1', 'Navoiy'), ('region2', 'Nurafshon'), ('region3', 'Zafarobod'), ('region4', 'Uchquduq')], max_length=20, null=True),
        ),
    ]
