# Generated by Django 3.0.5 on 2024-01-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_course_total_marks'),
        ('student', '0005_student_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regions',
            field=models.CharField(blank=True, choices=[('region1', 'Navoiy'), ('region2', 'Nurafshon'), ('region3', 'Zafarobod'), ('region4', 'Uchquduq'), ('region5', 'Nurobod')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='selected_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quiz.Course'),
        ),
    ]
