# Generated by Django 3.0.5 on 2023-12-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.IntegerField(default='1', help_text='Duration of the quiz in minutes'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
