# Generated by Django 3.0.5 on 2023-12-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
    ]
